USE escuela --DATOS GENERADOS CON IA-------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------PERSONA-------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO persona (primer_nombre, segundo_nombre, apellido_paterno, apellido_materno, direccion, correo_electronico, telefono) VALUES
('Juan', 'Carlos', 'Gomez', 'Lopez', 'Calle Principal 123', 'juan@gmail.com', '5037234567'),
('Maria', 'Luisa', 'Martinez', 'Perez', 'Av. Norte 456', 'maria@hotmail.com', '5036876543'),
('Pedro', NULL, 'Hernandez', 'Garcia', 'Calle Sur 789', 'pedro@gmail.com', '5037468109'),
('Ana', 'Sofia', 'Lopez', 'Diaz', 'Zona Centro 321', 'ana.s@hotmail.com', '5037357913'),
('Carlos', 'Eduardo', 'Ramirez', 'Jimenez', 'Calle Oriente 852', 'carlos.r@yahoo.com', '5036642098'),
('Luis', NULL, 'Gonzalez', 'Ortiz', 'Barrio Nuevo 963', 'luis@gmail.com', '5037112223'),
('Fernanda', 'Elena', 'Rojas', 'Castro', 'Colonia Jardines 741', 'fernanda@hotmail.com', '5036889997'),
('Ricardo', NULL, 'Castillo', 'Morales', 'Av. Las Palmas 753', 'ricardo@outlook.com', '5037233445'),
('Sandra', 'Isabel', 'Vargas', NULL, 'Pasaje San Jorge 654', 'sandra@gmail.com', '5036677889'),
('Javier', 'Alejandro', 'Chavez', 'Guzman', 'Calle Libertad 147', 'javier@yahoo.com', '5037788996'),
('Lucia', 'Alejandra', NULL, 'Mejia', 'Residencial Azul 369', 'lucia@hotmail.com', '5037566778'),
('Andres', 'Felipe', 'Villalobos', 'Mendez', 'Zona Norte 951', 'andres@gmail.com', '5037344552'),
('Gloria', 'Maria', 'Medina', 'Acosta', 'Calle Rosas 135', 'gloria@yahoo.com', '5036988776'),
('Antonio', NULL, 'Ponce', 'Zamora', 'Av. Arco Iris 468', 'antonio@gmail.com', '5036899001'),
('Paola', 'Andrea', 'Bermudez', 'Flores', 'Calle Larga 753', 'paola@hotmail.com', '5037455667'),
('Alejandra', NULL, 'Sosa', 'Campos', 'Calle Verde 246', 'alejandra@gmail.com', '5037322110'),
('Oscar', 'Rene', 'Reyes', 'Cruz', 'Residencial El Lago 489', 'oscar@hotmail.com', '5037566770'),
('Rafael', NULL, 'Nieto', 'Blanco', 'Barrio El Carmen 951', 'rafael@gmail.com', '5037029384'),
('Sara', 'Beatriz', 'Salinas', 'Paz', 'Calle Amanecer 753', 'sara@yahoo.com', '5037036485'),
('Diego', 'Daniel', NULL, 'Paredes', 'Zona Sur 369', 'diego@hotmail.com', '5037049582'),
('Gabriela', 'Estela', 'Torres', 'Campos', 'Pasaje Azul 159', 'gabriela@gmail.com', '5037059283'),
('Miguel', NULL, 'Figueroa', 'Silva', 'Calle Real 753', 'miguel@hotmail.com', '5037067382'),
('Daniela', 'Lorena', 'Aguilar', 'Soto', 'Colonia Sol 654', 'daniela@yahoo.com', '5036074839'),
('Victor', NULL, 'Carrillo', 'Rios', 'Residencial Brisas 357', 'victor@hotmail.com', '5036906721'),
('Marcos', 'David', 'Peralta', 'Franco', 'Av. San Jose 258', 'marcos@gmail.com', '5037238765'),
('Patricia', 'Karla', NULL, 'Guerrero', 'Calle Blanca 159', 'patricia@hotmail.com', '5037546872'),
('Camila', 'Rocio', 'Roldan', 'Galeano', 'Barrio Alto 951', 'camila@gmail.com', '5037682037'),
('Fabian', NULL, 'Estrada', 'Lara', 'Calle Dorada 753', 'fabian@yahoo.com', '5037093845'),
('Claudia', 'Del Carmen', 'Quintero', 'Navarro', 'Zona Bella 456', 'claudia@hotmail.com', '5036123965'),
('Eduardo', 'Daniel', 'Benitez', NULL, 'Colonia Alta 269', 'eduardo@gmail.com', '5036210378'),
('Monica', 'Beatriz', 'Ruiz', 'Muñoz', 'Calle Alegría 753', 'monica@hotmail.com', '5037324567'),
('Francisco', NULL, 'Arce', 'Guzman', 'Zona Rural 864', 'francisco@gmail.com', '5037418523'),
('Isabel', 'Cristina', 'Montes', 'Vega', 'Calle Paz 147', 'isabel@yahoo.com', '5036632587'),
('Julio', NULL, 'Acosta', 'Quijano', 'Residencial La Luna 951', 'julio@hotmail.com', '5037143587'),
('Lorena', 'Alejandra', 'Mejia', 'Rico', 'Barrio Flores 753', 'lorena@gmail.com', '5037156798'),
('Erick', NULL, 'Valenzuela', 'Moreno', 'Calle Principal 123', 'erick@hotmail.com', '5037267984'),
('Rosa', 'Clara', 'Sandoval', 'Lopez', 'Colonia Amistad 951', 'rosa@gmail.com', '5037378196'),
('Hector', NULL, 'Blanco', 'Ramirez', 'Av. Los Robles 357', 'hector@yahoo.com', '5037489302'),
('Andrea', 'Guadalupe', 'Ortega', 'Fernandez', 'Zona Oeste 468', 'andrea@gmail.com', '5036590213'),
('Pablo', NULL, 'Saenz', 'Galvez', 'Calle Nueva 753', 'pablo@hotmail.com', '5037903724'),
('Marta', 'Isabel', 'Navarro', 'Peña', 'Residencial Dorada 369', 'marta@gmail.com', '5036013245'),
('Ignacio', NULL, 'Delgado', 'Suarez', 'Calle Central 753', 'ignacio@hotmail.com', '5036124356'),
('Luisa', 'Marcela', 'Cabrera', 'Bravo', 'Zona Urbana 159', 'luisa@yahoo.com', '5037029483'),
('Cesar', NULL, 'Mendez', 'Villa', 'Colonia Verde 951', 'cesar@hotmail.com', '5037138495'),
('Elena', 'Carolina', 'Lugo', 'Serrano', 'Barrio Claro 357', 'elena@gmail.com', '5037248590'),
('Jorge', NULL, 'Fuentes', 'Gomez', 'Av. Central 456', 'jorge@yahoo.com', '5037359602'),
('Susana', 'Esther', 'Campos', 'Espinoza', 'Calle Este 753', 'susana@gmail.com', '5037468902'),
('Mario', NULL, 'Leal', 'Cortes', 'Zona Brisas 951', 'mario@hotmail.com', '5036579210'),
('Angela', 'Beatriz', 'Esquivel', 'Ramos', 'Residencial Jardín 753', 'angela@gmail.com', '5037689321'),
('Raul', NULL, 'Montoya', 'Cruz', 'Barrio Serenidad 258', 'raul@yahoo.com', '5036790432');
GO
INSERT INTO persona (primer_nombre, segundo_nombre, apellido_paterno, apellido_materno, direccion, correo_electronico, telefono) VALUES
('Mario', 'Eduardo', 'Lopez', NULL, 'Calle Primavera 101', 'mario.lopez@gmail.com', '5037234101'),
('Rosa', NULL, 'Perez', 'Gonzalez', 'Av. Central 202', 'rosa.perez@hotmail.com', '5037345202'),
('Pedro', 'Luis', 'Garcia', NULL, 'Barrio Norte 303', 'pedro.garcia@yahoo.com', '5037456303'),
('Carmen', 'Luisa', 'Martinez', 'Hernandez', 'Calle Real 404', 'carmen.martinez@gmail.com', '5037567404'),
('Alberto', NULL, 'Santos', 'Diaz', 'Residencial Sol 505', 'alberto.santos@hotmail.com', '5037678505'),
('Laura', 'Cristina', 'Ramos', NULL, 'Zona Jardines 606', 'laura.ramos@gmail.com', '5036789606'),
('Hector', 'Andres', NULL, 'Mendez', 'Calle Serena 707', 'hector.mendez@hotmail.com', '5037890707'),
('Ana', 'Patricia', 'Ruiz', 'Ortiz', 'Av. Esperanza 808', 'ana.ruiz@gmail.com', '5036901808'),
('Claudia', 'Estela', 'Jimenez', 'Paredes', 'Colonia Paz 909', 'claudia.jimenez@yahoo.com', '5036012909'),
('Miguel', NULL, 'Blanco', 'Navarro', 'Barrio Sol 101', 'miguel.blanco@gmail.com', '5037023101'),
('Paola', 'Alejandra', 'Guzman', NULL, 'Calle Norte 202', 'paola.guzman@hotmail.com', '5037134202'),
('Sebastian', NULL, 'Maldonado', 'Arce', 'Residencial Dorada 303', 'sebastian.maldonado@gmail.com', '5037245303'),
('Monica', 'Isabel', 'Nieto', NULL, 'Zona Bella Vista 404', 'monica.nieto@yahoo.com', '5037566404'),
('Ricardo', 'Esteban', NULL, 'Vega', 'Calle San Jose 505', 'ricardo.vega@gmail.com', '5037677505'),
('Lucia', NULL, 'Mejia', 'Campos', 'Barrio Amanecer 606', 'lucia.mejia@hotmail.com', '5036788606'),
('Gabriel', 'Antonio', 'Torres', NULL, 'Av. Principal 707', 'gabriel.torres@gmail.com', '5037899707'),
('Isabel', NULL, 'Salinas', 'Silva', 'Residencial Armonía 808', 'isabel.salinas@yahoo.com', '5036901808'),
('Diana', 'Claudia', NULL, 'Serrano', 'Calle Azul 909', 'diana.serrano@hotmail.com', '5036012909'),
('Julio', 'Rafael', 'Villalobos', NULL, 'Zona Luminosa 101', 'julio.villalobos@gmail.com', '5037024101'),
('Sara', NULL, 'Figueroa', 'Bermudez', 'Barrio Serena 202', 'sara.figueroa@gmail.com', '5037135202'),
('Juan', 'Fernando', 'Castro', NULL, 'Calle Paz 303', 'juan.castro@yahoo.com', '5037246303'),
('Patricia', NULL, 'Aguilar', 'Bravo', 'Residencial Sol 404', 'patricia.aguilar@gmail.com', '5037567404'),
('Rafael', 'Luis', 'Cruz', NULL, 'Zona Dorada 505', 'rafael.cruz@hotmail.com', '5037678505'),
('Emilia', NULL, 'Rico', 'Galeano', 'Barrio Sur 606', 'emilia.rico@gmail.com', '5036789606'),
('Oscar', 'Eduardo', NULL, 'Soto', 'Av. Norte 707', 'oscar.soto@yahoo.com', '5037890707'),
('Carolina', NULL, 'Blanco', 'Ortega', 'Calle Dorada 808', 'carolina.blanco@gmail.com', '5036901808'),
('Diego', 'Andres', 'Peralta', NULL, 'Zona Esmeralda 909', 'diego.peralta@hotmail.com', '5036012909'),
('Marta', NULL, 'Saenz', 'Suarez', 'Residencial Jardines 101', 'marta.saenz@gmail.com', '5037023101'),
('Valeria', 'Lorena', 'Dominguez', NULL, 'Barrio Nuevo 202', 'valeria.dominguez@hotmail.com', '5037134202'),
('Erick', NULL, 'Cabrera', 'Alvarado', 'Calle del Sol 303', 'erick.cabrera@gmail.com', '5037245303'),
('Laura', 'Paola', NULL, 'Delgado', 'Zona Norte 404', 'laura.delgado@yahoo.com', '5037566404'),
('Fernando', 'Esteban', 'Sanchez', NULL, 'Residencial Nueva 505', 'fernando.sanchez@gmail.com', '5037677505'),
('Veronica', NULL, 'Fuentes', 'Franco', 'Calle San Lucas 606', 'veronica.fuentes@hotmail.com', '5036788606'),
('Andres', NULL, NULL, 'Morales', 'Av. Estrella 707', 'andres.morales@gmail.com', '5037899707'),
('Hector', 'Luis', 'Vargas', NULL, 'Barrio Jardín 808', 'hector.vargas@yahoo.com', '5036901808'),
('Claudia', 'Alejandra', NULL, 'Ortiz', 'Zona Alta 909', 'claudia.ortiz@hotmail.com', '5036012909'),
('Jorge', NULL, 'Gomez', 'Salazar', 'Calle Real 101', 'jorge.gomez@gmail.com', '5037024101'),
('Ana', 'Maria', 'Hernandez', NULL, 'Barrio Serena 202', 'ana.hernandez@yahoo.com', '5037135202'),
('Pablo', NULL, NULL, 'Acosta', 'Residencial Esmeralda 303', 'pablo.acosta@gmail.com', '5037246303'),
('Monica', 'Cristina', 'Navarro', NULL, 'Av. Central 404', 'monica.navarro@hotmail.com', '5037567404'),
('Sofia', NULL, 'Mendoza', 'Jimenez', 'Zona Dorada 505', 'sofia.mendoza@gmail.com', '5037678505'),
('Francisco', 'Ruben', 'Campos', NULL, 'Calle Paz 606', 'francisco.campos@gmail.com', '5036789606'),
('Elena', NULL, 'Reyes', 'Cruz', 'Barrio del Sol 707', 'elena.reyes@yahoo.com', '5037890707'),
('Luis', NULL, NULL, 'Peña', 'Zona Vista 808', 'luis.pena@hotmail.com', '5036901808'),
('Susana', 'Lorena', 'Quintero', NULL, 'Av. Norte 909', 'susana.quintero@gmail.com', '5036012909'),
('Camila', NULL, 'Paredes', 'Lopez', 'Residencial Jardín 101', 'camila.paredes@hotmail.com', '5037023101'),
('Renata', 'Alejandra', 'Ortega', NULL, 'Calle Luz 202', 'renata.ortega@gmail.com', '5037134202'),
('Julian', NULL, 'Saenz', 'Villa', 'Zona Serena 303', 'julian.saenz@yahoo.com', '5037245303'),
('Clara', NULL, 'Silva', 'Rosales', 'Residencial Sol 404', 'clara.silva@gmail.com', '5037566404'),
('Alfredo', 'Manuel', 'Acosta', NULL, 'Av. Real 505', 'alfredo.acosta@gmail.com', '5037677505');
GO
INSERT INTO persona (primer_nombre, segundo_nombre, apellido_paterno, apellido_materno, direccion, correo_electronico, telefono) VALUES
('Laura', 'Cristina', 'Rojas', 'Martinez', 'Calle Principal 100', 'laura@gmail.com', '5037234001'),
('Jose', NULL, 'Ramirez', 'Guzman', 'Barrio Norte 202', 'jose@yahoo.com', '5037345002'),
('Karen', 'Mariela', 'Lopez', 'Santos', 'Colonia Brisas 303', 'karen@hotmail.com', '5037456003'),
('Luis', 'Fernando', 'Gonzalez', 'Hernandez', 'Calle Oeste 404', 'luisf@gmail.com', '5037567004'),
('Daniel', 'Antonio', 'Perez', 'Vargas', 'Residencial Las Palmas 505', 'danielp@gmail.com', '5037678005'),
('Claudia', 'Isabel', 'Mendoza', 'Diaz', 'Zona Sur 606', 'claudiai@hotmail.com', '5036789006'),
('Francisco', 'Miguel', 'Cruz', 'Ortega', 'Calle Este 707', 'francisco@gmail.com', '5037890007'),
('Veronica', 'Carolina', 'Castillo', 'Rivera', 'Av. Central 808', 'vero@yahoo.com', '5036901008'),
('Fernando', NULL, 'Chavez', 'Jimenez', 'Barrio Verde 909', 'fernando@gmail.com', '5036012009'),
('Susana', 'Alejandra', 'Reyes', 'Alvarado', 'Calle Azul 101', 'susanaa@gmail.com', '5037233010'),
('Javier', NULL, 'Nieto', 'Campos', 'Residencial Florencia 202', 'javiern@gmail.com', '5037564011'),
('Sofia', 'Paula', 'Salazar', 'Miranda', 'Zona Oro 303', 'sofia@yahoo.com', '5037455012'),
('Ricardo', 'Esteban', 'Figueroa', 'Bermudez', 'Calle Dorada 404', 'ricardo@gmail.com', '5036786013'),
('Adriana', NULL, 'Vega', 'Cortes', 'Colonia Bella 505', 'adriana@hotmail.com', '5037347014'),
('Carlos', 'David', 'Mejia', 'Paredes', 'Zona Nueva 606', 'carlosd@gmail.com', '5037678015'),
('Lucia', 'Maria', 'Blanco', 'Guerrero', 'Calle Real 707', 'luciam@yahoo.com', '5037890016'),
('Diego', 'Andres', 'Benitez', 'Sandoval', 'Residencial Dorada 808', 'diegob@gmail.com', '5036901017'),
('Elena', NULL, 'Maldonado', 'Acosta', 'Av. Los Arcos 909', 'elena@gmail.com', '5036012018'),
('Miguel', 'Alejandro', 'Torres', 'Rico', 'Zona Centro 101', 'miguel@yahoo.com', '5037023019'),
('Rosa', 'Beatriz', 'Peralta', 'Sosa', 'Colonia Armonía 202', 'rosa@gmail.com', '5037134020'),
('Oscar', NULL, 'Lopez', 'Villalobos', 'Barrio San Jose 303', 'oscar@yahoo.com', '5037245021'),
('Ana', 'Claudia', 'Morales', 'Lara', 'Calle Amanecer 404', 'anac@gmail.com', '5037566022'),
('Paola', 'Elena', 'Guzman', 'Rosales', 'Residencial Nuevo Horizonte 505', 'paolae@gmail.com', '5037677023'),
('Josefina', NULL, 'Mendez', 'Hidalgo', 'Av. Principal 606', 'josefina@gmail.com', '5036788024'),
('Sandra', 'Cristina', 'Martinez', 'Perez', 'Calle de las Flores 808', 'sandra@gmail.com', '5036901026'),
('Gabriel', NULL, 'Hernandez', 'Jimenez', 'Barrio Jardines 909', 'gabriel@yahoo.com', '5036012027'),
('Andrea', 'Sofia', 'Diaz', 'Serrano', 'Zona Baja 101', 'andreas@gmail.com', '5037023028'),
('Mario', NULL, 'Ramos', 'Espinoza', 'Calle Clara 202', 'marior@gmail.com', '5037134029'),
('Diana', 'Lorena', 'Paredes', 'Silva', 'Residencial Bella Vista 303', 'diana@yahoo.com', '5037245030'),
('Hector', 'Rene', 'Acosta', 'Villa', 'Av. Dorada 404', 'hector@gmail.com', '5037566037'),
('Monica', NULL, 'Zamora', 'Nieto', 'Zona Del Sol 505', 'monica@yahoo.com', '5037677037'),
('Jaime', 'Roberto', 'Ortega', 'Suarez', 'Barrio Alto 606', 'jaime@gmail.com', '5036788037'),
('Marcela', NULL, 'Reyes', 'Mora', 'Calle Luz 707', 'marcela@hotmail.com', '5037890037'),
('Raul', 'Eduardo', 'Navarro', 'Quijano', 'Zona Brillante 808', 'raule@gmail.com', '5036901037'),
('Patricia', NULL, 'Villalobos', 'Gonzalez', 'Residencial El Lago 909', 'patricia@gmail.com', '5036012036'),
('Emilia', 'Paola', 'Rivas', 'Garcia', 'Calle Vista Hermosa 101', 'emiliap@yahoo.com', '5037023037'),
('Sebastian', NULL, 'Cabrera', 'Castro', 'Av. Real 202', 'sebastian@gmail.com', '5037134036'),
('Leticia', 'Del Carmen', 'Silva', 'Delgado', 'Zona Verde 303', 'leticiad@yahoo.com', '5037245036'),
('Alfonso', NULL, 'Dominguez', 'Galeano', 'Residencial Jardín 404', 'alfonso@gmail.com', '5037566040'),
('Cecilia', 'Rocio', 'Castillo', 'Acosta', 'Zona Maravilla 505', 'cecilia@hotmail.com', '5037677041'),
('Elias', NULL, 'Fuentes', 'Arias', 'Barrio Sereno 606', 'elias@gmail.com', '5036788042'),
('Luz', 'Clara', 'Mora', 'Ortega', 'Calle Alondra 707', 'luzc@gmail.com', '5037890043'),
('Esteban', NULL, 'Perez', 'Bravo', 'Zona del Norte 808', 'esteban@yahoo.com', '5036901044'),
('Regina', 'Luisa', 'Sanchez', 'Escobar', 'Residencial Horizonte 909', 'regina@gmail.com', '5036012045'),
('Camilo', NULL, 'Blanco', 'Nieto', 'Barrio Paz 101', 'camilo@yahoo.com', '5037023046'),
('Valeria', 'Marcela', 'Quintero', 'Arce', 'Calle San Juan 202', 'valeria@gmail.com', '5037134047'),
('Ignacio', NULL, 'Soto', 'Rico', 'Zona Estrella 303', 'ignacios@gmail.com', '5037245048'),
('Renata', 'Andrea', 'Ruiz', 'Santos', 'Residencial Victoria 404', 'renataa@gmail.com', '5037566049'),
('Tomas', NULL, 'Saenz', 'Galvez', 'Av. Esperanza 505', 'tomas@gmail.com', '5037677050'),
('Luz', 'Leticia', 'Mejia', 'Guzman', 'Calle Enriqueta 707', 'let5zc@gmail.com', '5037881042');
GO
INSERT INTO persona (primer_nombre, segundo_nombre, apellido_paterno, apellido_materno, direccion, correo_electronico, telefono) VALUES
('Carlos', 'Eduardo', 'Vargas', 'Martinez', 'Av. Dorada 151', 'carlos.vargas@gmail.com', '5037234151'),
('Laura', NULL, 'Gomez', 'Lopez', 'Zona Serena 152', 'laura.gomez@yahoo.com', '5037345152'),
('Luis', 'Antonio', 'Hernandez', NULL, 'Calle Clara 153', 'luis.h@hotmail.com', '5037456153'),
('Mariela', 'Cristina', NULL, 'Santos', 'Residencial Sol 154', 'mariela.santos@gmail.com', '5037567154'),
('Francisco', 'Jose', 'Rivera', NULL, 'Barrio del Sol 155', 'francisco.r@yahoo.com', '5037678155'),
('Sofia', 'Beatriz', 'Perez', 'Garcia', 'Av. Norte 156', 'sofia.perez@gmail.com', '5036789156'),
('Claudia', 'Rocio', 'Vega', 'Jimenez', 'Calle San Lucas 157', 'claudia.vega@hotmail.com', '5037890157'),
('Miguel', NULL, 'Maldonado', 'Arce', 'Residencial Bella Vista 158', 'miguel.maldonado@gmail.com', '5036901158'),
('Ana', 'Paola', 'Lopez', NULL, 'Zona Esperanza 159', 'ana.lopez@gmail.com', '5036012159'),
('Ricardo', 'Esteban', 'Campos', NULL, 'Calle Nueva 160', 'ricardo.campos@yahoo.com', '5037023160'),
('Patricia', NULL, 'Blanco', 'Navarro', 'Zona Baja 161', 'patricia.blanco@gmail.com', '5037134161'),
('Diego', 'Rene', 'Villalobos', NULL, 'Av. Principal 162', 'diego.v@gmail.com', '5037245162'),
('Lucia', NULL, 'Acosta', 'Suarez', 'Calle Real 163', 'lucia.acosta@hotmail.com', '5037566163'),
('Jorge', 'Antonio', 'Paredes', 'Mora', 'Barrio San Jose 164', 'jorge.paredes@gmail.com', '5037677164'),
('Monica', NULL, NULL, 'Sandoval', 'Residencial Luz 165', 'monica.sandoval@yahoo.com', '5036788165'),
('Rosa', 'Alejandra', 'Rico', NULL, 'Zona Centro 166', 'rosa.rico@gmail.com', '5037890166'),
('Julio', NULL, 'Peña', 'Villa', 'Calle Clara 167', 'julio.pena@gmail.com', '5036901167'),
('Paola', 'Cristina', NULL, 'Quijano', 'Zona del Norte 168', 'paola.quijano@hotmail.com', '5036012168'),
('Alberto', NULL, 'Ramirez', 'Delgado', 'Barrio Paz 169', 'alberto.ramirez@gmail.com', '5037023169'),
('Gabriel', 'Luis', 'Vargas', NULL, 'Av. Dorada 170', 'gabriel.vargas@yahoo.com', '5037134170'),
('Adriana', NULL, 'Guzman', 'Flores', 'Residencial Nueva 171', 'adriana.guzman@gmail.com', '5037245171'),
('Sebastian', NULL, 'Rivas', NULL, 'Zona Bella Vista 172', 'sebastian.rivas@hotmail.com', '5037566172'),
('Marta', 'Rocio', 'Torres', 'Cruz', 'Calle Esmeralda 173', 'marta.torres@gmail.com', '5037677173'),
('Francisco', NULL, 'Lopez', 'Silva', 'Residencial Sol 174', 'francisco.lopez@yahoo.com', '5036788174'),
('Leticia', 'Clara', 'Nieto', NULL, 'Zona Serena 175', 'leticia.nieto@gmail.com', '5037890175'),
('Julian', NULL, 'Salazar', 'Jimenez', 'Barrio Jardín 176', 'julian.salazar@hotmail.com', '5036901176'),
('Monica', 'Isabel', NULL, 'Mendoza', 'Calle del Sol 177', 'monica.mendoza@gmail.com', '5036012177'),
('Jose', NULL, 'Morales', 'Perez', 'Zona del Sur 178', 'jose.morales@yahoo.com', '5037023178'),
('Isabel', 'Rocio', 'Ortega', NULL, 'Residencial del Norte 179', 'isabel.ortega@gmail.com', '5037134179'),
('Raul', 'Luis', 'Aguilar', NULL, 'Av. Clara 180', 'raul.aguilar@hotmail.com', '5037245180'),
('Valeria', NULL, 'Quintero', 'Paredes', 'Zona Estrella 181', 'valeria.q@gmail.com', '5037566181'),
('Emilia', 'Paola', 'Campos', NULL, 'Residencial Serena 182', 'emilia.campos@yahoo.com', '5037677182'),
('Oscar', NULL, 'Saenz', 'Bermudez', 'Barrio Claro 183', 'oscar.saenz@gmail.com', '5036788183'),
('Sandra', 'Claudia', 'Cabrera', NULL, 'Zona Alta 184', 'sandra.cabrera@hotmail.com', '5037890184'),
('Ruben', NULL, 'Mendez', 'Bravo', 'Av. Principal 185', 'ruben.mendez@gmail.com', '5036901185'),
('Diana', 'Rocio', 'Fuentes', NULL, 'Calle Clara 186', 'diana.fuentes@yahoo.com', '5036012186'),
('Luis', NULL, NULL, 'Villa', 'Residencial Luz 187', 'luis.villa@hotmail.com', '5037023187'),
('Gabriela', 'Alejandra', 'Blanco', NULL, 'Barrio Jardines 188', 'gabriela.blanco@gmail.com', '5037134188'),
('Clara', NULL, 'Hidalgo', 'Franco', 'Zona Bella Vista 189', 'clara.h@gmail.com', '5037245189'),
('Julio', 'Rene', 'Ponce', NULL, 'Calle del Norte 190', 'julio.ponce@yahoo.com', '5037566190'),
('Marcos', NULL, 'Cortes', 'Jimenez', 'Barrio Nuevo 191', 'marcos.cortes@gmail.com', '5037677191'),
('Elena', 'Cristina', 'Suarez', NULL, 'Zona Real 192', 'elena.suarez@hotmail.com', '5036788192'),
('Pablo', NULL, 'Navarro', 'Garcia', 'Residencial Clara 193', 'pablo.navarro@gmail.com', '5037890193'),
('Renata', 'Paola', 'Mejia', NULL, 'Barrio Dorado 194', 'renata.mejia@hotmail.com', '5036901194'),
('Hector', NULL, 'Vega', 'Flores', 'Zona del Sol 195', 'hector.vega@gmail.com', '5036012195'),
('Marcela', 'Claudia', 'Sandoval', NULL, 'Residencial Jardín 196', 'marcela.s@gmail.com', '5037023196'),
('Rocio', NULL, 'Bermudez', 'Villa', 'Barrio Esmeralda 197', 'rocio.b@hotmail.com', '5037134197'),
('Fernando', 'Luis', 'Rico', NULL, 'Zona del Sur 198', 'fernando.rico@gmail.com', '5037245198'),
('Monica', NULL, 'Perez', 'Jimenez', 'Residencial Nueva 199', 'monica.perez@yahoo.com', '5037566199'),
('Sara', 'Isabel', 'Delgado', NULL, 'Barrio del Sol 200', 'sara.d@gmail.com', '5037677200');
GO
-------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------GRADO---------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO grado (nGrado, aula, ubicacion, descripcion) VALUES
('Primero', 'Primero A', 'Edificio 01 Primera Planta', 'Cerca de la entrada principal'),
('Primero', 'Primero B', 'Edificio 01 Primera Planta', 'Cerca de las escaleras'),
('Segundo', 'Segundo A', 'Edificio 01 Primera Planta', 'Junto al aula de Primero B'),
('Segundo', 'Segundo B', 'Edificio 01 Primera Planta', 'Cerca de la biblioteca'),
('Tercero', 'Tercero A', 'Edificio 01 Primera Planta', 'Cerca del laboratorio'),
('Tercero', 'Tercero B', 'Edificio 01 Primera Planta', 'Junto a las ventanas'),
('Cuarto', 'Cuarto A', 'Edificio 02 Primera Planta', 'Cerca del patio de recreo'),
('Cuarto', 'Cuarto B', 'Edificio 02 Primera Planta', 'Junto al aula de Cuarto A'),
('Quinto', 'Quinto A', 'Edificio 02 Primera Planta', 'Cerca de la sala de profesores'),
('Quinto', 'Quinto B', 'Edificio 02 Primera Planta', 'Junto al aula de Quinto A'),
('Sexto', 'Sexto A', 'Edificio 02 Primera Planta', 'Cerca de las escaleras'),
('Sexto', 'Sexto B', 'Edificio 02 Primera Planta', 'Junto al área de almacenamiento'),
('Séptimo', 'Séptimo A', 'Edificio 01 Segunda Planta', 'Cerca de la entrada principal'),
('Séptimo', 'Séptimo B', 'Edificio 01 Segunda Planta', 'Junto a las ventanas'),
('Octavo', 'Octavo A', 'Edificio 01 Segunda Planta', 'Junto al aula de Séptimo B'),
('Octavo', 'Octavo B', 'Edificio 01 Segunda Planta', 'Cerca del pasillo central'),
('Noveno', 'Noveno A', 'Edificio 01 Segunda Planta', 'Cerca del laboratorio de ciencias'),
('Noveno', 'Noveno B', 'Edificio 01 Segunda Planta', 'Junto al área de proyectos'),
('Primero Bach. Gral.', 'General A', 'Edificio 01 Tercera Planta', 'Cerca del patio trasero'),
('Primero Bach. Gral.', 'General B', 'Edificio 02 Tercera Planta', 'Junto a las ventanas'),
('Segundo Bach. Gral.', 'General A', 'Edificio 01 Tercera Planta', 'Cerca del laboratorio de informática'),
('Segundo Bach. Gral.', 'General B', 'Edificio 02 Tercera Planta', 'Junto al aula de General A'),
('Primero Bach. Tec.', '1° Bach. Tec. A', 'Edificio 01 Tercera Planta', 'Cerca de las escaleras principales'),
('Primero Bach. Tec.', '1° Bach. Tec. B', 'Edificio 02 Tercera Planta', 'Junto al aula de Primero Bach. A'),
('Segundo Bach. Tec.', '2° Bach. Tec. A', 'Edificio 01 Tercera Planta', 'Cerca del laboratorio de informática'),
('Segundo Bach. Tec.', '2° Bach. Tec. B', 'Edificio 02 Tercera Planta', 'Junto al área de proyectos grupales'),
('Tercero Bach. Tec.', '3° Bach. Tec. A', 'Edificio 01 Tercera Planta', 'Cerca de la entrada norte'),
('Tercero Bach. Tec.', '3° Bach. Tec. B', 'Edificio 02 Tercera Planta', 'Cerca del aula de música');
GO
-----------CARGGO--------------------------------------------------------------------------------------------------------------------------------------------------
INSERT INTO cargo (ncargo, descripcion) VALUES
('Director', 'Encargado de la administración general y supervisión de la escuela'),
('Subdirector', 'Apoya al director en la gestión administrativa y académica'),
('Maestro de Matemáticas', 'Enseña conceptos matemáticos y guía el aprendizaje numérico'),
('Maestro de Ciencias', 'Imparte clases relacionadas con física, química y biología'),
('Maestro de Sociales', 'Explica temas históricos, geográficos y sociales'),
('Maestro de Lenguaje', 'Guía en habilidades de lectura, escritura y expresión oral'),
('Maestro de Inglés', 'Enseña gramática y comunicación en el idioma inglés'),
('Bibliotecario', 'Administra la biblioteca y fomenta hábitos de lectura en estudiantes'),
('Secretario', 'Gestiona tareas administrativas y documentales del plantel'),
('Tesorero', 'Administra los recursos financieros y presupuestarios de la escuela'),
('Encargado de Ornato', 'Mantiene el orden y limpieza en las instalaciones escolares'),
('Conserje', 'Realiza labores de limpieza y mantenimiento general'),
('Vigilante', 'Supervisa la seguridad del personal y las instalaciones escolares'),
('Enfermero', 'Brinda atención médica básica en situaciones de emergencia'),
('Maestro Ciencias Naturales', 'tiene diversas disciplinas científicas para comprender el mundo natural y sus fenómenos.'),
('Técnico Informático', 'Administra y da soporte a los equipos tecnológicos de la escuela'),
('Coordinador Académico', 'Supervisa y organiza las actividades académicas del plantel'),
('Coodinador Refrigerio', 'Gestiona la planificación y distribución de alimentos en la cafetería'),
('Maestro de Arte', 'Desarrolla las habilidades artísticas de los estudiantes'),
('Maestro de Historia', 'Imparte conocimientos sobre historia universal y nacional'),
('Maestro de Educación Física', 'Promueve la actividad física y el deporte escolar'),
('Maestro de Idiomas (Francés)', 'Enseña el idioma francés para la comunicación y el aprendizaje cultural'),
('Maestro de Tecnología', 'Educa sobre herramientas tecnológicas y habilidades digitales'),
('Coordinador cultural', 'Promueve y organiza actividades culturales en la escuela'),
('Ayudante General', 'Apoya en diversas tareas operativas dentro del plantel escolar'),
('Inspector Escolar', 'Supervisa la disciplina y el cumplimiento de las normas escolares'),
('Personal de Apoyo', 'Colabora en tareas generales para el funcionamiento de la institución'),
('Encargado de Cafetería', 'Administra los alimentos y servicios de la cafetería de la escuela'),
('Asesor Pedagógico', 'Proporciona estrategias educativas al personal docente'),
('Encargado de Materiales', 'Gestiona el inventario de materiales educativos y recursos escolares'),
('Operador de Equipo', 'Maneja el uso de equipos audiovisuales y tecnológicos'),
('Encargado de Recursos Humanos', 'Gestiona la contratación, bienestar y desarrollo del personal'),
('Encargado de Laboratorio', 'Supervisa y organiza las actividades experimentales en el laboratorio'),
('Contador', 'Administra los balances financieros y reportes contables de la escuela'),
('Encargado de Inventario', 'Controla el registro y distribución de materiales y suministros'),
('Recepcionista', 'Asiste en la atención al público y la recepción de documentos'),
('Encargado de Transporte', 'Gestiona el traslado seguro de los estudiantes'),
('Auxiliar de Enfermería', 'Asiste al enfermero en brindar atención médica básica'),
('Asistente Técnico', 'Apoya en tareas tecnológicas y administrativas del plantel'),
('Director de Deportes', 'Coordina las actividades deportivas y organiza competencias escolares'),
('Gestor de Actividades', 'Planifica y organiza talleres y eventos extracurriculares'),
('Encargado de Talleres', 'Supervisa actividades manuales y prácticas para los estudiantes'),
('Profesor de Tecnología', 'Imparte conocimientos en informática y habilidades digitales'),
('Coordinador de Cultura', 'Fomenta el desarrollo cultural con eventos y actividades artísticas'),
('Administrador', 'Supervisa los recursos humanos, materiales y financieros del plantel'),
('Encargado de Suministros', 'Gestiona la compra y distribución de materiales escolares'),
('Encargado de Comunicación', 'Promueve la relación de la escuela con la comunidad educativa'),
('Cocinera(o)', 'Prepara los alimentos para los estudiantes y personal escolar'),
('Ayudante de Cocina', 'Apoya en la preparación y distribución de alimentos en la cafetería');